version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt

  build:
    commands:
      - echo Running tests with pytest...
      # Add src to Python path so packages are found
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/src
      - pytest --junitxml=pytest-report.xml --cov=src --cov-report=xml:coverage.xml

artifacts:
  files:
    - pytest-report.xml
    - coverage.xml
    - dist/*.whl

