[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg"
version = "0.1.4"
description = "CI practice package"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "Matthew Gonzalez" }]
dependencies = []

