name: Python CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true
          pip install -r requirements-dev.txt || true
          pip install pytest pytest-cov build twine boto3 ruff

      - name: Ruff lint
        run: ruff check .

      - name: Run tests with coverage
        run: |
          pytest --junitxml=pytest-report.xml --cov=src --cov-report=xml:coverage.xml

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: reports-${{ matrix.python-version }}
          path: |
            pytest-report.xml
            coverage.xml

      - name: Build wheel
        run: python -m build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload wheel(s) to S3
        run: |
          aws s3 cp dist/ s3://mg-actions-artifacts-2k25/ --recursive --exclude "*" --include "*.whl"

      - name: Get CodeArtifact auth token
        id: ca
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain mg-domain \
            --domain-owner 959305806236 \
            --query authorizationToken --output text)
          echo "token=$TOKEN" >> $GITHUB_OUTPUT

      - name: Upload wheel to CodeArtifact via Twine
        env:
          TWINE_USERNAME: aws
          TWINE_PASSWORD: ${{ steps.ca.outputs.token }}
        run: |
          REPO_URL="https://mg-domain-959305806236.d.codeartifact.us-west-2.amazonaws.com/pypi/mg-repo/"
          twine upload --repository-url "${REPO_URL}simple/" dist/*.whl

